//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace RPMWare.Api.Client.RPMWareOrder {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OrderSoap", Namespace="https://secure.rpmware.com/api")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApiModelBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(int[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Order : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddLineItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddTrackingNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderIdsSinceLastOrderIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrdersByCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrdersSinceLastOrderIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Order() {
            this.Url = global::RPMWare.Api.Client.Properties.Settings.Default.RPMWare_Api_Client_RPMWareOrder_Order;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddHistoryCompletedEventHandler AddHistoryCompleted;
        
        /// <remarks/>
        public event AddLineItemCompletedEventHandler AddLineItemCompleted;
        
        /// <remarks/>
        public event AddTrackingNumberCompletedEventHandler AddTrackingNumberCompleted;
        
        /// <remarks/>
        public event GetOrderCompletedEventHandler GetOrderCompleted;
        
        /// <remarks/>
        public event GetOrderIdsSinceLastOrderIdCompletedEventHandler GetOrderIdsSinceLastOrderIdCompleted;
        
        /// <remarks/>
        public event GetOrdersCompletedEventHandler GetOrdersCompleted;
        
        /// <remarks/>
        public event GetOrdersByCustomerCompletedEventHandler GetOrdersByCustomerCompleted;
        
        /// <remarks/>
        public event GetOrdersSinceLastOrderIdCompletedEventHandler GetOrdersSinceLastOrderIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.rpmware.com/api/AddHistory", RequestNamespace="https://secure.rpmware.com/api", ResponseNamespace="https://secure.rpmware.com/api", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result AddHistory(string apiToken, int orderId, string note) {
            object[] results = this.Invoke("AddHistory", new object[] {
                        apiToken,
                        orderId,
                        note});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void AddHistoryAsync(string apiToken, int orderId, string note) {
            this.AddHistoryAsync(apiToken, orderId, note, null);
        }
        
        /// <remarks/>
        public void AddHistoryAsync(string apiToken, int orderId, string note, object userState) {
            if ((this.AddHistoryOperationCompleted == null)) {
                this.AddHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddHistoryOperationCompleted);
            }
            this.InvokeAsync("AddHistory", new object[] {
                        apiToken,
                        orderId,
                        note}, this.AddHistoryOperationCompleted, userState);
        }
        
        private void OnAddHistoryOperationCompleted(object arg) {
            if ((this.AddHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddHistoryCompleted(this, new AddHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.rpmware.com/api/AddLineItem", RequestNamespace="https://secure.rpmware.com/api", ResponseNamespace="https://secure.rpmware.com/api", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result AddLineItem(string apiToken, int orderId, int itemId, decimal price, int quantity) {
            object[] results = this.Invoke("AddLineItem", new object[] {
                        apiToken,
                        orderId,
                        itemId,
                        price,
                        quantity});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void AddLineItemAsync(string apiToken, int orderId, int itemId, decimal price, int quantity) {
            this.AddLineItemAsync(apiToken, orderId, itemId, price, quantity, null);
        }
        
        /// <remarks/>
        public void AddLineItemAsync(string apiToken, int orderId, int itemId, decimal price, int quantity, object userState) {
            if ((this.AddLineItemOperationCompleted == null)) {
                this.AddLineItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddLineItemOperationCompleted);
            }
            this.InvokeAsync("AddLineItem", new object[] {
                        apiToken,
                        orderId,
                        itemId,
                        price,
                        quantity}, this.AddLineItemOperationCompleted, userState);
        }
        
        private void OnAddLineItemOperationCompleted(object arg) {
            if ((this.AddLineItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddLineItemCompleted(this, new AddLineItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.rpmware.com/api/AddTrackingNumber", RequestNamespace="https://secure.rpmware.com/api", ResponseNamespace="https://secure.rpmware.com/api", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result AddTrackingNumber(string apiToken, int orderId, string shippingMethod, string trackingNumber, string notes) {
            object[] results = this.Invoke("AddTrackingNumber", new object[] {
                        apiToken,
                        orderId,
                        shippingMethod,
                        trackingNumber,
                        notes});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void AddTrackingNumberAsync(string apiToken, int orderId, string shippingMethod, string trackingNumber, string notes) {
            this.AddTrackingNumberAsync(apiToken, orderId, shippingMethod, trackingNumber, notes, null);
        }
        
        /// <remarks/>
        public void AddTrackingNumberAsync(string apiToken, int orderId, string shippingMethod, string trackingNumber, string notes, object userState) {
            if ((this.AddTrackingNumberOperationCompleted == null)) {
                this.AddTrackingNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddTrackingNumberOperationCompleted);
            }
            this.InvokeAsync("AddTrackingNumber", new object[] {
                        apiToken,
                        orderId,
                        shippingMethod,
                        trackingNumber,
                        notes}, this.AddTrackingNumberOperationCompleted, userState);
        }
        
        private void OnAddTrackingNumberOperationCompleted(object arg) {
            if ((this.AddTrackingNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddTrackingNumberCompleted(this, new AddTrackingNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.rpmware.com/api/GetOrder", RequestNamespace="https://secure.rpmware.com/api", ResponseNamespace="https://secure.rpmware.com/api", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result GetOrder(string apiToken, int id) {
            object[] results = this.Invoke("GetOrder", new object[] {
                        apiToken,
                        id});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderAsync(string apiToken, int id) {
            this.GetOrderAsync(apiToken, id, null);
        }
        
        /// <remarks/>
        public void GetOrderAsync(string apiToken, int id, object userState) {
            if ((this.GetOrderOperationCompleted == null)) {
                this.GetOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderOperationCompleted);
            }
            this.InvokeAsync("GetOrder", new object[] {
                        apiToken,
                        id}, this.GetOrderOperationCompleted, userState);
        }
        
        private void OnGetOrderOperationCompleted(object arg) {
            if ((this.GetOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderCompleted(this, new GetOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.rpmware.com/api/GetOrderIdsSinceLastOrderId", RequestNamespace="https://secure.rpmware.com/api", ResponseNamespace="https://secure.rpmware.com/api", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result GetOrderIdsSinceLastOrderId(string apiToken, int lastOrderId) {
            object[] results = this.Invoke("GetOrderIdsSinceLastOrderId", new object[] {
                        apiToken,
                        lastOrderId});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderIdsSinceLastOrderIdAsync(string apiToken, int lastOrderId) {
            this.GetOrderIdsSinceLastOrderIdAsync(apiToken, lastOrderId, null);
        }
        
        /// <remarks/>
        public void GetOrderIdsSinceLastOrderIdAsync(string apiToken, int lastOrderId, object userState) {
            if ((this.GetOrderIdsSinceLastOrderIdOperationCompleted == null)) {
                this.GetOrderIdsSinceLastOrderIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderIdsSinceLastOrderIdOperationCompleted);
            }
            this.InvokeAsync("GetOrderIdsSinceLastOrderId", new object[] {
                        apiToken,
                        lastOrderId}, this.GetOrderIdsSinceLastOrderIdOperationCompleted, userState);
        }
        
        private void OnGetOrderIdsSinceLastOrderIdOperationCompleted(object arg) {
            if ((this.GetOrderIdsSinceLastOrderIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderIdsSinceLastOrderIdCompleted(this, new GetOrderIdsSinceLastOrderIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.rpmware.com/api/GetOrders", RequestNamespace="https://secure.rpmware.com/api", ResponseNamespace="https://secure.rpmware.com/api", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result GetOrders(string apiToken) {
            object[] results = this.Invoke("GetOrders", new object[] {
                        apiToken});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrdersAsync(string apiToken) {
            this.GetOrdersAsync(apiToken, null);
        }
        
        /// <remarks/>
        public void GetOrdersAsync(string apiToken, object userState) {
            if ((this.GetOrdersOperationCompleted == null)) {
                this.GetOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrdersOperationCompleted);
            }
            this.InvokeAsync("GetOrders", new object[] {
                        apiToken}, this.GetOrdersOperationCompleted, userState);
        }
        
        private void OnGetOrdersOperationCompleted(object arg) {
            if ((this.GetOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrdersCompleted(this, new GetOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.rpmware.com/api/GetOrdersByCustomer", RequestNamespace="https://secure.rpmware.com/api", ResponseNamespace="https://secure.rpmware.com/api", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result GetOrdersByCustomer(string apiToken, int customerId) {
            object[] results = this.Invoke("GetOrdersByCustomer", new object[] {
                        apiToken,
                        customerId});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrdersByCustomerAsync(string apiToken, int customerId) {
            this.GetOrdersByCustomerAsync(apiToken, customerId, null);
        }
        
        /// <remarks/>
        public void GetOrdersByCustomerAsync(string apiToken, int customerId, object userState) {
            if ((this.GetOrdersByCustomerOperationCompleted == null)) {
                this.GetOrdersByCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrdersByCustomerOperationCompleted);
            }
            this.InvokeAsync("GetOrdersByCustomer", new object[] {
                        apiToken,
                        customerId}, this.GetOrdersByCustomerOperationCompleted, userState);
        }
        
        private void OnGetOrdersByCustomerOperationCompleted(object arg) {
            if ((this.GetOrdersByCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrdersByCustomerCompleted(this, new GetOrdersByCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.rpmware.com/api/GetOrdersSinceLastOrderId", RequestNamespace="https://secure.rpmware.com/api", ResponseNamespace="https://secure.rpmware.com/api", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result GetOrdersSinceLastOrderId(string apiToken, int lastOrderId) {
            object[] results = this.Invoke("GetOrdersSinceLastOrderId", new object[] {
                        apiToken,
                        lastOrderId});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrdersSinceLastOrderIdAsync(string apiToken, int lastOrderId) {
            this.GetOrdersSinceLastOrderIdAsync(apiToken, lastOrderId, null);
        }
        
        /// <remarks/>
        public void GetOrdersSinceLastOrderIdAsync(string apiToken, int lastOrderId, object userState) {
            if ((this.GetOrdersSinceLastOrderIdOperationCompleted == null)) {
                this.GetOrdersSinceLastOrderIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrdersSinceLastOrderIdOperationCompleted);
            }
            this.InvokeAsync("GetOrdersSinceLastOrderId", new object[] {
                        apiToken,
                        lastOrderId}, this.GetOrdersSinceLastOrderIdOperationCompleted, userState);
        }
        
        private void OnGetOrdersSinceLastOrderIdOperationCompleted(object arg) {
            if ((this.GetOrdersSinceLastOrderIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrdersSinceLastOrderIdCompleted(this, new GetOrdersSinceLastOrderIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://secure.rpmware.com/api")]
    public partial class Result {
        
        private object dataField;
        
        private string messageField;
        
        private string successField;
        
        /// <remarks/>
        public object Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Order1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Address))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Customer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerLevel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderHistory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderLineItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Payment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderTracking))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://secure.rpmware.com/api")]
    public partial class ApiModelBase {
        
        private System.DateTime dateAddedField;
        
        private System.DateTime dateModifiedField;
        
        private int idField;
        
        /// <remarks/>
        public System.DateTime DateAdded {
            get {
                return this.dateAddedField;
            }
            set {
                this.dateAddedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Order", Namespace="https://secure.rpmware.com/api")]
    public partial class Order1 : ApiModelBase {
        
        private Address billingAddressField;
        
        private string couponCodeField;
        
        private string couponNameField;
        
        private Customer customerField;
        
        private string customerCommentsField;
        
        private OrderHistory[] historyField;
        
        private OrderLineItem[] lineItemsField;
        
        private string orderNoField;
        
        private string orderStatusField;
        
        private decimal orderTotalField;
        
        private Payment[] paymentsField;
        
        private Address shippingAddressField;
        
        private decimal shippingAmountField;
        
        private string shippingMethodField;
        
        private decimal taxAmountField;
        
        private OrderTracking[] trackingNumbersField;
        
        /// <remarks/>
        public Address BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        public string CouponCode {
            get {
                return this.couponCodeField;
            }
            set {
                this.couponCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CouponName {
            get {
                return this.couponNameField;
            }
            set {
                this.couponNameField = value;
            }
        }
        
        /// <remarks/>
        public Customer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerComments {
            get {
                return this.customerCommentsField;
            }
            set {
                this.customerCommentsField = value;
            }
        }
        
        /// <remarks/>
        public OrderHistory[] History {
            get {
                return this.historyField;
            }
            set {
                this.historyField = value;
            }
        }
        
        /// <remarks/>
        public OrderLineItem[] LineItems {
            get {
                return this.lineItemsField;
            }
            set {
                this.lineItemsField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        public decimal OrderTotal {
            get {
                return this.orderTotalField;
            }
            set {
                this.orderTotalField = value;
            }
        }
        
        /// <remarks/>
        public Payment[] Payments {
            get {
                return this.paymentsField;
            }
            set {
                this.paymentsField = value;
            }
        }
        
        /// <remarks/>
        public Address ShippingAddress {
            get {
                return this.shippingAddressField;
            }
            set {
                this.shippingAddressField = value;
            }
        }
        
        /// <remarks/>
        public decimal ShippingAmount {
            get {
                return this.shippingAmountField;
            }
            set {
                this.shippingAmountField = value;
            }
        }
        
        /// <remarks/>
        public string ShippingMethod {
            get {
                return this.shippingMethodField;
            }
            set {
                this.shippingMethodField = value;
            }
        }
        
        /// <remarks/>
        public decimal TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        public OrderTracking[] TrackingNumbers {
            get {
                return this.trackingNumbersField;
            }
            set {
                this.trackingNumbersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://secure.rpmware.com/api")]
    public partial class Address : ApiModelBase {
        
        private string accountNameField;
        
        private string cityField;
        
        private string countryField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string stateField;
        
        private string streetAddress1Field;
        
        private string streetAddress2Field;
        
        private string zipField;
        
        /// <remarks/>
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string StreetAddress1 {
            get {
                return this.streetAddress1Field;
            }
            set {
                this.streetAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string StreetAddress2 {
            get {
                return this.streetAddress2Field;
            }
            set {
                this.streetAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://secure.rpmware.com/api")]
    public partial class Customer : ApiModelBase {
        
        private string accountNameField;
        
        private Address[] addressesField;
        
        private CustomerLevel customerLevelField;
        
        private string emailField;
        
        private string faxField;
        
        private Order1[] ordersField;
        
        private string phone1Field;
        
        private string phone2Field;
        
        /// <remarks/>
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        public Address[] Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        public CustomerLevel CustomerLevel {
            get {
                return this.customerLevelField;
            }
            set {
                this.customerLevelField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public Order1[] Orders {
            get {
                return this.ordersField;
            }
            set {
                this.ordersField = value;
            }
        }
        
        /// <remarks/>
        public string Phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
            }
        }
        
        /// <remarks/>
        public string Phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://secure.rpmware.com/api")]
    public partial class CustomerLevel : ApiModelBase {
        
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://secure.rpmware.com/api")]
    public partial class OrderHistory : ApiModelBase {
        
        private string notesField;
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://secure.rpmware.com/api")]
    public partial class OrderLineItem : ApiModelBase {
        
        private string brandNameField;
        
        private decimal extendedPriceField;
        
        private int itemIdField;
        
        private string partNumberField;
        
        private decimal priceField;
        
        private string productGroupNameField;
        
        private int quantityField;
        
        /// <remarks/>
        public string BrandName {
            get {
                return this.brandNameField;
            }
            set {
                this.brandNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal ExtendedPrice {
            get {
                return this.extendedPriceField;
            }
            set {
                this.extendedPriceField = value;
            }
        }
        
        /// <remarks/>
        public int ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        public string PartNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string ProductGroupName {
            get {
                return this.productGroupNameField;
            }
            set {
                this.productGroupNameField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://secure.rpmware.com/api")]
    public partial class Payment : ApiModelBase {
        
        private string authorizationNumberField;
        
        private int creditCardExpirationMonthField;
        
        private int creditCardExpirationYearField;
        
        private string creditCardNumberField;
        
        private decimal paymentAmountField;
        
        private string paymentStatusField;
        
        private string paymentTypeField;
        
        private string transactionNumberField;
        
        /// <remarks/>
        public string AuthorizationNumber {
            get {
                return this.authorizationNumberField;
            }
            set {
                this.authorizationNumberField = value;
            }
        }
        
        /// <remarks/>
        public int CreditCardExpirationMonth {
            get {
                return this.creditCardExpirationMonthField;
            }
            set {
                this.creditCardExpirationMonthField = value;
            }
        }
        
        /// <remarks/>
        public int CreditCardExpirationYear {
            get {
                return this.creditCardExpirationYearField;
            }
            set {
                this.creditCardExpirationYearField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardNumber {
            get {
                return this.creditCardNumberField;
            }
            set {
                this.creditCardNumberField = value;
            }
        }
        
        /// <remarks/>
        public decimal PaymentAmount {
            get {
                return this.paymentAmountField;
            }
            set {
                this.paymentAmountField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentStatus {
            get {
                return this.paymentStatusField;
            }
            set {
                this.paymentStatusField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionNumber {
            get {
                return this.transactionNumberField;
            }
            set {
                this.transactionNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://secure.rpmware.com/api")]
    public partial class OrderTracking : ApiModelBase {
        
        private string notesField;
        
        private string shippingMethodField;
        
        private string trackingNumberField;
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public string ShippingMethod {
            get {
                return this.shippingMethodField;
            }
            set {
                this.shippingMethodField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AddHistoryCompletedEventHandler(object sender, AddHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AddLineItemCompletedEventHandler(object sender, AddLineItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddLineItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddLineItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AddTrackingNumberCompletedEventHandler(object sender, AddTrackingNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddTrackingNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddTrackingNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOrderCompletedEventHandler(object sender, GetOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOrderIdsSinceLastOrderIdCompletedEventHandler(object sender, GetOrderIdsSinceLastOrderIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderIdsSinceLastOrderIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderIdsSinceLastOrderIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOrdersCompletedEventHandler(object sender, GetOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOrdersByCustomerCompletedEventHandler(object sender, GetOrdersByCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrdersByCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrdersByCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOrdersSinceLastOrderIdCompletedEventHandler(object sender, GetOrdersSinceLastOrderIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrdersSinceLastOrderIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrdersSinceLastOrderIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591